#!/usr/bin/env perl
use strict;
use warnings;
use Test::More tests => 2;

use FindBin qw($Bin);
use lib "$Bin/../lib";
use Day08;

my $solution = Solution->new( fh => *DATA );
is $solution->part1(), 14, "Part1";
is $solution->part2(), 34, "Part2";

__DATA__
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
