#!/usr/bin/env perl
use v5.38;
use Test2::V0;

use FindBin qw($Bin);
use lib "$Bin/../lib";
use Day08;

my $solution = Solution->new( fh => *DATA );
is $solution->part1(), 14, "Part1";
is $solution->part2(), 34, "Part2";

done_testing();

__DATA__
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
