name: OCaml 2023

on:
  push:
    branches: [main]
    paths:
      - "2023/ocaml/**"
  pull_request:
    branches: [main]
    paths:
      - "2023/ocaml/**"

defaults:
  run:
    working-directory: ./2023/ocaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1.x
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
