name: Rust 2023

on:
  push:
    branches: [main]
    paths:
      - "2023/rust/**"
  pull_request:
    branches: [main]
    paths:
      - "2023/rust/**"

defaults:
  run:
    working-directory: ./2023/rust

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Build with features
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose

  clippy:
    env:
      RUSTFLAGS: "-Dwarnings"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
